# Generated by Django 4.2.11 on 2026-03-26 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chess_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesscompetition',
            name='tournament_type',
            field=models.CharField(choices=[('swiss', 'Swiss System'), ('knockout', 'Knockout'), ('round_robin', 'Round Robin')], default='swiss', max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_participants', models.ManyToManyField(blank=True, related_name='user_profiles', to='chess_app.chessparticipant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create_match', 'Create Match'), ('update_match', 'Update Match'), ('delete_match', 'Delete Match'), ('create_participant', 'Create Participant'), ('update_participant', 'Update Participant'), ('delete_participant', 'Delete Participant'), ('swiss_pairing', 'Swiss Pairing')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='chess_app.chessmatch')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='chess_app.chessparticipant')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='chess_app_a_timesta_4b4c3a_idx'), models.Index(fields=['admin_user', '-timestamp'], name='chess_app_a_admin_u_c5d5d5_idx'), models.Index(fields=['action_type', '-timestamp'], name='chess_app_a_action__3a6f77_idx')],
            },
        ),
    ]
