# Generated by Django 4.2.11 on 2026-03-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0002_chesscompetition_tournament_type_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesscompetition',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
