# Generated by Django 4.2.11 on 2026-03-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0003_chesscompetition_registration_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lichess_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
