# Generated by Django 4.2.11 on 2026-03-27 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0004_userprofile_lichess_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessmatch',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to='chess_app.chessparticipant'),
        ),
    ]
