# Generated by Django 4.2.11 on 2026-03-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0006_add_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chessmatch',
            new_name='chess_app_c_competi_cc7447_idx',
            old_name='chess_app_m_comp_created_idx',
        ),
        migrations.RenameIndex(
            model_name='chessmatch',
            new_name='chess_app_c_player1_0885b4_idx',
            old_name='chess_app_m_p1_created_idx',
        ),
        migrations.RenameIndex(
            model_name='chessmatch',
            new_name='chess_app_c_player2_79dfb8_idx',
            old_name='chess_app_m_p2_created_idx',
        ),
        migrations.RenameIndex(
            model_name='chessparticipant',
            new_name='chess_app_c_lichess_744edf_idx',
            old_name='chess_app_p_lichess_idx',
        ),
    ]
